### ISSUE TITLE
nutrient API product does not output

### ISSUE THREAD

**Issue by sbeaulieu** [WHOIGit/nes-lter-ims#39]
uploaded new nutrients EXCEL sheet and new sample log sheet.
nutrients: same columns new data for 5 cruises appended rows. LTER_Sample_ID differs from Nutrient_Number for cruises EN655 and EN657 and EN649. It looks like should merge on Nutrient_Number.
sample log: 5 new columns

**Comment by ecrockford** [comment]
LTER_sample_log extension was changed from .xls to .xlsx maybe this could be the problem? 

Yes we changed the header column from Nutrient_Number to LTER_Sample_ID after adding OOI_Sample_ID to the work flow. 

LTER_sample_log.xlsx has 2 new columns: Nut_Falcon_tube_a & Nut_Falcon_tube_b.

**Comment by ecrockford** [comment]
Nut_Falcon_tube_a & Nut_Falcon_tube_b are basically the equivalent of LTER_sample_ID and are just differentiating protocol used for sample collection. If we officially change protocol down the line to using sterilized Falcon tubes as opposed to acid washed scintillation vials, one set of columns will become obsolete. I didn't really account for this when choosing to add new columns. 

Maybe we should discuss a different strategy of adding a column for nutrient method instead of separate columns of sample type? This would result in duplicate rows in the sample log to be able to fit all of the nutrients. Would that be an issue? We have a nut_c column but that wouldn't work because I was thinking a single nutrient method column as opposed to method column for each individual sample.

**Comment by ecrockford** [comment]
Stace and Taylor chatted and we *believe* to fix the output, when referencing the LTERnut.xlsx, the ID column "Nutrient Number" should be used and not "LTER sample ID". (Sorry about that! The column naming is very misleading.)  

We think line 85 of /nes-lter/ims/neslter/parsing/nut/nut.py needs to be changed and then maybe we'll be fixed! 

https://github.com/WHOIGit/nes-lter-ims/blob/master/neslter/parsing/nut/nut.py#L85

**Comment by joefutrelle** [comment]
`sample_id` also referenced on [this line](https://github.com/WHOIGit/nes-lter-ims/blob/71859da8450ddfb98141bbbdd27159142d26c55f/neslter/parsing/nut/nut.py#L76)

**Comment by joefutrelle** [comment]
> LTER_sample_log extension was changed from .xls to .xlsx maybe this could be the problem?

That is certainly causing nut output to fail, independently of the other issues identified here.

**Comment by joefutrelle** [comment]
After correcting the filename, nut output is produced as expected.
